module.exports = {
  accompaniment: [
    { name: 'Piano' },
    { name: 'Brass Quintet' },
    { name: 'Organ' },
    { name: 'Handbells' },
    { name: 'Clarinet' },
    { name: 'Tenor Saxophone' },
    { name: 'Soprano Saxophone' },
    { name: 'Trumpet' },
    { name: 'Flugelhorn' },
    { name: 'Alto Saxophone' },
  ],
  arrangers: [
    { name: 'Ken Berg' },
    { name: 'Joshua Jacobson' },
    { name: 'Mac Huff' },
    { name: 'Gerald Gurss' },
    { name: 'Pentatonix' },
    { name: 'Paul Anthony' },
    { name: 'Tim McKnight' },
    { name: 'Kevin Robison' },
    { name: 'Janet Pummill' },
  ],
  lyricists: [
    { name: 'Henry van Dyke' },
    { name: 'St. Augustine' },
    { name: 'Billy Hayes' },
    { name: 'Jay Johnson' },
    { name: 'Randi Driscoll' },
    { name: 'Jay Livingston' },
    { name: 'Ray Evans' },
    { name: 'Robert MacGimsey' },
    { name: 'Corlynn Hanney' },
  ],
  composers: [
    { name: 'Corlynn Hanney' },
    { name: 'Robert MacGimsey' },
    { name: 'Jay Livingston' },
    { name: 'Ray Evans' },
    { name: 'Randi Driscoll' },
    { name: 'Katherine Kennicott Davis' },
    { name: 'Carey' },
    { name: 'Afanasieff' },
    { name: 'Weiss' },
    { name: 'Thiele' },
    { name: 'Billy Hayes' },
    { name: 'Jay Johnson' },
    { name: 'Ola Gjeilo' },
    { name: 'Tom Lehrer' },
    { name: 'Ken Berg' },
    { name: 'Ludwig van Beethoven' },
  ],
  occasions: [{ name: 'Holiday' }, { name: 'Christmas' }],
  seedMusic: [
    {
      title: 'All I Want for Christmas/What a Wonderful World',
      voices: 'SATB',
      quantityOnHand: 54,
      accompaniments: ['Piano'],
      composers: ['Carey', 'Afanasieff', 'Weiss', 'Thiele'],
      arrangers: ['Gerald Gurss'],
      occasions: ['Holiday'],
      performances: ['Ghosts of Christmas Past'],
    },
    {
      title: 'Sweet Little Jesus Boy',
      voices: 'SATB, Soprano Solo',
      style: 'a cappella',
      publisher: 'Carl Fisher, LLC',
      quantityOnHand: 55,
      purchasePrice: 1.6,
      composers: ['Robert MacGimsey'],
      lyricists: ['Robert MacGimsey'],
      arrangers: ['Janet Pummill'],
      occasions: ['Christmas'],
      performances: ['Ghosts of Christmas Past'],
    },
    {
      title: 'Silver Bells',
      description: 'From the Paramount Picture THE LEMON DROP KID',
      voices: 'SATB',
      duration: '4:40',
      publisher: 'ATV Music Publishing LLC',
      quantityOnHand: 57,
      purchasePrice: 1.95,
      accompaniments: ['Piano'],
      composers: ['Jay Livingston', 'Ray Evans'],
      lyricists: ['Jay Livingston', 'Ray Evans'],
      arrangers: ['Kevin Robison'],
      occasions: ['Holiday'],
      performances: ['Ghosts of Christmas Past'],
    },
    {
      title: 'Love Is Love',
      voices: 'SATB, Solo',
      publisher: 'Yelton Rhodes Music (BMI)',
      style: 'Secular',
      quantityOnHand: 77,
      purchasePrice: 2.25,
      accompaniments: ['Piano'],
      composers: ['Randi Driscoll'],
      lyricists: ['Randi Driscoll'],
      arrangers: ['Tim McKnight', 'Kevin Robison'],
      performances: ['Ghosts of Christmas Past'],
    },
    {
      title: 'Little Drummer Boy',
      voices: 'SATB',
      style: 'a cappella',
      publisher: 'Music Haven',
      quantityOnHand: 53,
      composers: ['Katherine Kennicott Davis'],
      arrangers: ['Pentatonix', 'Paul Anthony'],
      occasions: ['Christmas'],
      performances: ['Ghosts of Christmas Past'],
    },
    {
      title: 'Blue Christmas',
      voices: 'SATB, Solo',
      duration: '4:00',
      style: '50s Doo-wop',
      publisher: 'Polygram International Publishing, Inc.',
      quantityOnHand: 57,
      purchasePrice: 2.25,
      accompaniments: ['Piano'],
      composers: ['Billy Hayes', 'Jay Johnson'],
      lyricists: ['Billy Hayes', 'Jay Johnson'],
      arrangers: ['Mac Huff'],
      occasions: ['Holiday'],
      performances: ['Ghosts of Christmas Past'],
    },
    {
      title: 'Evening Prayer',
      voices: 'SATB divisi',
      style: 'Sacred',
      publisher: 'Walton Music Corporation',
      quantityOnHand: 76,
      purchasePrice: 2.25,
      accompaniments: [
        'Piano',
        'Tenor Saxophone',
        'Soprano Saxophone',
        'Trumpet',
        'Flugelhorn',
        'Alto Saxophone',
      ],
      composers: ['Ola Gjeilo'],
      lyricists: ['St. Augustine'],
      performances: ['Ghosts of Christmas Past'],
    },
    {
      title: 'Chanukah in Santa Monica',
      voices: 'SATB',
      publisher: 'Transcontinental Music Publications',
      quantityOnHand: 56,
      purchasePrice: 2.95,
      accompaniments: ['Piano', 'Clarinet'],
      composers: ['Tom Lehrer'],
      arrangers: ['Joshua Jacobson'],
      occasions: ['Holiday'],
      performances: ['Ghosts of Christmas Past'],
    },
    {
      title: 'Joyful, Joyful, We Adore Thee',
      voices: 'SATB',
      style: 'Sacred',
      publisher: 'MorningStar Music Publishers, Inc.',
      quantityOnHand: 58,
      accompaniments: ['Piano', 'Brass Quintet', 'Organ', 'Handbells'],
      composers: ['Ludwig van Beethoven', 'Ken Berg'],
      lyricists: ['Henry van Dyke'],
      performances: ['Ghosts of Christmas Past'],
    },
    {
      title: 'Christmas Angel',
      voices: 'SATB, Solo',
      publisher: 'Cypress Choral Music',
      quantityOnHand: 75,
      purchasePrice: 1.95,
      accompaniments: ['Piano'],
      composers: ['Corlynn Hanney'],
      lyricists: ['Corlynn Hanney'],
      occasions: ['Christmas'],
      performances: ['Ghosts of Christmas Past'],
    },
  ],
};
