export const LOAD_LIBRARY_REQUEST = 'LOAD_LIBRARY_REQUEST';
export const LOAD_LIBRARY_SUCCESS = 'LOAD_LIBRARY_SUCCESS';
export const LOAD_LIBRARY_FAILURE = 'LOAD_LIBRARY_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
